export const GET_PRODUCTS="GET_PRODUCTS";
export const GET_PRODUCT="GET_PRODUCT";
export const IS_FETCHING_PRODUCTS="IS_FETCHING_PRODUCTS";
export const IS_FETCHING_PRODUCT="IS_FETCHING_PRODUCT";
export const IS_FETCHING_PRODUCTS_ERROR="IS_FETCHING_PRODUCTS_ERROR";
export const IS_FETCHING_PRODUCT_ERROR="IS_FETCHING_PRODUCT_ERROR";


export const ADD_TO_CART="ADD_TO_CART";
export const INCREASE_CART_QTY="INCREASE_CART_QTY";
export const DECREASE_CART_QTY="DECREASE_CART_QTY";
export const REMOVE_CART="REMOVE_CART";
export const CLEAR_CART="CLEAR_CART";

export const IS_SUBMITING_ORDER="IS_SUBMITING_ORDER";
export const CHANGE_DEV_FORM_FIELD="CHANGE_DEV_FORM_FIELD";
export const IS_SUBMITTING_ERROR="IS_SUBMITTING_ERROR";
export const ORDER_SUCCESS="ORDER_SUCCESS";
// export const DEV_FORM_FIELD="DEV_FORM_FIELD";

